name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PAT_DECRAPIFIER }}'
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.0
    - run: yarn install --immutable
    - run: yarn run test:ci || touch FAIL_JOB
    - run: yarn run lint:ci || touch FAIL_JOB
    - name: pre-danger
      run: git config user.email "decrapifier@govspend.com" && git config user.name "Decrapifier" && git checkout ${{github.head_ref}} && git config push.default upstream && git branch -u origin/${{github.head_ref}}
    - run: yarn run danger
      env:
        DANGER_GITHUB_API_TOKEN: '${{ secrets.PAT_DECRAPIFIER }}'
    - name: check-if-lint-or-test-runs-failed
      run: 'if test -f "FAIL_JOB"; then exit 1; fi'
