export let options = [
  { value: 'Field1', field: 'Field1', typeDefault: 'number', label: 'Field 1' },
  { value: 'Field2', field: 'Field2', typeDefault: 'number', label: 'Field 2' },
  { value: 'GroupA.FieldA', field: 'GroupA.FieldA', typeDefault: 'number', label: 'Field A' },
  { value: 'GroupA.FieldB', field: 'GroupA.FieldB', typeDefault: 'number', label: 'Field B' },
  { value: 'GroupA.FieldC', field: 'GroupA.FieldC', typeDefault: 'number', label: 'Field C' },
  { value: 'GroupA.FieldD', field: 'GroupA.FieldD', typeDefault: 'number', label: 'Field D' },
  { value: 'GroupA.FieldE', field: 'GroupA.FieldE', typeDefault: 'number', label: 'Field E' },
  { value: 'GroupA.FieldF', field: 'GroupA.FieldF', typeDefault: 'number', label: 'Field F' },
  { value: 'GroupA.FieldG', field: 'GroupA.FieldG', typeDefault: 'number', label: 'Field G' },
  { value: 'GroupA.FieldH', field: 'GroupA.FieldH', typeDefault: 'number', label: 'Field H' },
  { value: 'GroupA.FieldI', field: 'GroupA.FieldI', typeDefault: 'number', label: 'Field I' },
  { value: 'GroupA.FieldJ', field: 'GroupA.FieldJ', typeDefault: 'number', label: 'Field J' },
  { value: 'GroupA.GroupB.FieldB1', field: 'GroupA.GroupB.FieldB1', typeDefault: 'facet', label: 'Field B1' },
  { value: 'GroupA.GroupB.FieldB2', field: 'GroupA.GroupB.FieldB2', typeDefault: 'facet', label: 'Field B2' },
  { value: 'GroupA.GroupB.GroupC.FieldC1', field: 'GroupA.GroupB.GroupC.FieldC1', typeDefault: 'number', label: 'Field C1' },
  { value: 'GroupA.GroupB.GroupC.FieldC2', field: 'GroupA.GroupB.GroupC.FieldC2', typeDefault: 'number', label: 'Field C2' },
]
