export let options = [
  { value: 'Field1', field: 'Field1', typeDefault: 'number', label: 'Field 1' },
  { value: 'Field2', field: 'Field2', typeDefault: 'number', label: 'Field 2' },
  {
    value: 'GroupA.FieldA.value',
    field: 'GroupA.FieldA.value',
    typeDefault: 'number',
    label: 'value',
  },
  {
    value: 'GroupA.FieldB.name',
    field: 'GroupA.FieldB.name',
    typeDefault: 'string',
    label: 'name',
  },
  {
    value: 'GroupA.FieldC.value',
    field: 'GroupA.FieldC.value',
    typeDefault: 'number',
    label: 'value',
  },
  {
    value: 'GroupA.FieldC.name',
    field: 'GroupA.FieldC.name',
    typeDefault: 'string',
    label: 'name',
  },
  {
    value: 'GroupA.FieldD',
    field: 'GroupA.FieldD',
    typeDefault: 'number',
    label: 'Field D',
  },
  {
    value: 'GroupA.FieldE',
    field: 'GroupA.FieldE',
    typeDefault: 'number',
    label: 'Field E',
  },
  {
    value: 'GroupA.FieldF',
    field: 'GroupA.FieldF',
    typeDefault: 'number',
    label: 'Field F',
  },
  {
    value: 'GroupA.FieldG',
    field: 'GroupA.FieldG',
    typeDefault: 'number',
    label: 'Field G',
  },
  {
    value: 'GroupA.FieldH',
    field: 'GroupA.FieldH',
    typeDefault: 'number',
    label: 'Field H',
  },
  {
    value: 'GroupA.FieldI',
    field: 'GroupA.FieldI',
    typeDefault: 'number',
    label: 'Field I',
  },
  {
    value: 'GroupA.FieldJ',
    field: 'GroupA.FieldJ',
    typeDefault: 'number',
    label: 'Field J',
  },
  {
    value: 'GroupA.GroupB.FieldB1',
    field: 'GroupA.GroupB.FieldB1',
    typeDefault: 'facet',
    label: 'Field B1',
  },
  {
    value: 'GroupA.GroupB.FieldB2',
    field: 'GroupA.GroupB.FieldB2',
    typeDefault: 'facet',
    label: 'Field B2',
  },
  {
    value: 'GroupA.GroupB.GroupC.FieldC1',
    field: 'GroupA.GroupB.GroupC.FieldC1',
    typeDefault: 'number',
    label: 'Field C1',
  },
  {
    value: 'GroupA.GroupB.GroupC.FieldC2',
    field: 'GroupA.GroupB.GroupC.FieldC2',
    typeDefault: 'number',
    label: 'Field C2',
  },
  // Commonly Used Section Examples
  // these fields belong to parents with only one field and will rollup to the next parent in the nested picker
  {
    value: 'GroupA.GroupB.FieldC1',
    field: 'GroupA.GroupB.FieldC1',
    label: 'Rolled Up Field GroupB.FieldC1',
    typeDefault: 'number',
    isCommonlyUsed: true,
  },
  {
    value: 'GroupF.FieldE1',
    field: 'GroupF.FieldE1',
    label: 'Rolled Up Field GroupF.FieldE1',
    typeDefault: 'number',
    isCommonlyUsed: true,
  },
  // fields that do not require rolling up to the next parent but will group under the Commonly Used Fields group in the nested picker
  {
    value: 'GroupA.GroupC.FieldD1',
    field: 'GroupA.GroupC.FieldD1',
    label: 'FieldD1',
    typeDefault: 'number',
    isCommonlyUsed: true,
  },
  {
    value: 'GroupA.GroupC.FieldD2',
    field: 'GroupA.GroupC.FieldD2',
    label: 'FieldD2',
    typeDefault: 'number',
    isCommonlyUsed: true,
  },
]
