#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# If changesets found, bump versions and update changelogs, otherwise do nothing
yarn changeset version

# Exit if no changes are generated by the version command above
if [ -z "$(git status --porcelain)" ]; then
  exit 0
fi

# Possibly setup authentication with npm
if [ ! -z "$NPM_AUTH_TOKEN" ]; then
  echo "npmAuthToken: $NPM_AUTH_TOKEN" >> ~/.yarnrc.yml
fi

# Test npm authentication before committing
yarn npm whoami

# Set bot user name if not set
if [ ! "$(git config --get user.name)" ]; then
  git config user.name 'Publishing Bot'
fi

# Set bot user email if not set
if [ ! "$(git config --get user.email)" ]; then
  git config user.email 'publishing-bot@govspend.com'
fi

git commit --all --message "Bump versions and update changelogs"

git push

yarn changeset publish
