version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint-ci
      - run:
          name: test
          command: npm run test-ci
      - run:
          name: pre-danger
          command: git config user.email "decrapifier@govspend.us" && git config user.name "Decrapifier" && git config push.default upstream && git branch -u origin/$CIRCLE_BRANCH
          when: always
      - run:
          name: danger
          command: npm run duti
          when: always
      - deploy:
          name: Maybe Deploy Library
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish
            fi
      - deploy:
          name: Maybe Deploy Storybook
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy-storybook
            fi
