name: Push to master

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.0
    - run: yarn install --immutable
    - run: yarn test
    - name: Publish to npm
      run: |
        echo 'npmRegistryServer: "https://registry.npmjs.org/"\nnpmAuthToken: "$NPM_TOKEN"' > ./.yarnrc
        yarn publish
      env:
        NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
