name: Lint, Test, and Danger

on: pull_request

jobs:
  lint-test-danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_DECRAPIFIER }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          eslint_command_prefix: yarn
          prettier: true
          prettier_command_prefix: yarn

      - name: Test
        run: yarn run test --ci --coverage --reporters github-actions --reporters summary

      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          delete-old-comments: true

      - name: Run danger
        run: |
          git config user.email "decrapifier@govspend.com"
          git config user.name "Decrapifier"
          git config push.default upstream
          git checkout --track origin/${{github.head_ref}} || true
          yarn run danger ci -d dangerfile.cjs
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.PAT_DECRAPIFIER }}
