name: Lint, Test, and Danger

on: pull_request

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  lint-test-danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --immutable

      - uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          eslint_command_prefix: yarn
          prettier: true
          prettier_command_prefix: yarn

      - run: yarn run jest --ci --reporters github-actions --reporters summary --coverage .
        env:
          NODE_OPTIONS: '--no-warnings --experimental-vm-modules'

      - uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          delete-old-comments: true

      - run: yarn run danger ci -d dangerfile.cjs
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
